services:
  postgres:

    image: postgres:16
    container_name: postgres_container
    
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DBNAME}
    
    env_file:
      - ./.env

    ports:
      - 5433:5432

    volumes:
      - ./postgres-db-volume/data:/var/lib/postgresql/data
    
    healthcheck:
      test: ["CMD", "pg_isready", "-U" ,"${POSTGRES_USER}"]
      interval: 10s
      retries: 5
      start_period: 5s
    
    restart: always

    networks:
      - app-connections


  airflow:

    build:
      context : .
      dockerfile : Dockerfile

    image: custom-airflow
    container_name: airflow_container

    env_file:
      - ./.env

    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${DB_USER}:${DB_PASSWORD}@postgres:${PORT}/${DBNAME}

    volumes:
      - ./airflow/dags:/opt/airflow/dags:z
      - ./airflow/plugins:/opt/airflow/plugins:z
      - ./airflow/logs:/opt/airflow/logs:z
      - ./airflow/config:/opt/airflow/daconfiggconfigs:z
      - ./scraper:/opt/scraper
    
    ports:
      - 8080:8080
    
    user: "${AIRFLOW_UID:-50000}:0"

    command: >
      bash -c "airflow db migrate && airflow standalone"

    networks:
      - app-connections
      
    depends_on:
      postgres:
        condition: service_healthy



networks:
  app-connections:
    driver: bridge